### ISSUE TITLE
Something wrong with subscription block

### ISSUE THREAD

**Issue by mdrahiem** [rebelchris/daily-dev-tips#25]
<img width="1101" alt="image" src="https://user-images.githubusercontent.com/12086760/178922690-cc9300c9-ec7d-48f8-acec-2ed2ed922e5d.png">

<img width="1790" alt="image" src="https://user-images.githubusercontent.com/12086760/178922964-51934f02-a108-4683-b264-0baae83a6bc7.png">

**Comment by rebelchris** [comment]
Thanks for logging @mdrahiem on it :)

**Comment by rebelchris** [comment]
@mdrahiem should be fixed now :) 
Cloudflare was being very strict 😅
